image: alpine:latest
# this task runner should be runned only when pushing to production .
pages:
  stage: deploy
  script:
    - echo 'Updating Documentation Logo ...'
    - cp public/assets/images/logo.png  documentation/images
    - echo 'Updating server...'
    - curl https://forge.laravel.com/servers/99311/sites/228092/deploy/http?token=cJoYAWYO8cpbO6fqxiJACBSa2D7SbY47CcSdaGu9
  artifacts:
    paths:
    - documentation

  only:
  - master

